
START TRANSACTION;
INSERT INTO customer
	(customer_id, store_id, first_name, last_name, address_id)
VALUES (9999, 2, 'Jay', 'Bracken', '7');
COMMIT;

DELETE FROM customer
WHERE customer_id = 9999;

ROLLBACK;

SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;
START TRANSACTION;
SELECT * FROM customer;
COMMIT;

SET TRANSACTION ISOLATION LEVEL READ COMMITTED;
START TRANSACTION;
SELECT * FROM customer;
COMMIT;

SET TRANSACTION ISOLATION LEVEL REPEATABLE READ;
START TRANSACTION;
SELECT * FROM customer;
COMMIT;

